//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.BL.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Application.BL.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Слой для отображения нижней части текстуры.
        /// </summary>
        internal static string Desc_BackLayer {
            get {
                return ResourceManager.GetString("Desc_BackLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список реакций на клавиатурные нажатия.
        /// </summary>
        internal static string Desc_BindSections {
            get {
                return ResourceManager.GetString("Desc_BindSections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доступен ли виджет и все его дочерние виджеты для реакций. Может влиять на внешний вид (виджет &quot;засеривается&quot;). По умолчанию true.
        /// </summary>
        internal static string Desc_Enabled {
            get {
                return ResourceManager.GetString("Desc_Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Визуальная прозрачность виджета. По умолчанию 1.0f - непрозрачен.
        /// </summary>
        internal static string Desc_Fade {
            get {
                return ResourceManager.GetString("Desc_Fade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Уведомление о наведении на виджет вне зависимости от его доступности для кликов. (Использовать только при сильной необходимости - потребляет много ресурсов.).
        /// </summary>
        internal static string Desc_ForceReactionOnPointing {
            get {
                return ResourceManager.GetString("Desc_ForceReactionOnPointing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Игнорировать PickChildrenOnly при скролировании колесом мыши и наведении. Всегда обрабатывать реакцию скролла колесом мыши.
        /// </summary>
        internal static string Desc_ForceWheel {
            get {
                return ResourceManager.GetString("Desc_ForceWheel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Слой для отображения верхней части текстуры.
        /// </summary>
        internal static string Desc_FrontLayer {
            get {
                return ResourceManager.GetString("Desc_FrontLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Игнорировать двойной клик мышью для виджета и для его детей.
        /// </summary>
        internal static string Desc_IgnoreDblClick {
            get {
                return ResourceManager.GetString("Desc_IgnoreDblClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запрещать ли пользовательским аддонам операции с виджетом. По умолчанию false.
        /// </summary>
        internal static string Desc_IsProtected {
            get {
                return ResourceManager.GetString("Desc_IsProtected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Системное название виджета.
        /// </summary>
        internal static string Desc_Name {
            get {
                return ResourceManager.GetString("Desc_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обрабатывать мышиные реакции только для детей этого виджета, игнорируя сам виджет.
        /// </summary>
        internal static string Desc_PickChildrenOnly {
            get {
                return ResourceManager.GetString("Desc_PickChildrenOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Черно-белая текстура (по степеням 2) для задания активной (белые пиксели) области для кликов мышью. Нужно вручную выставлять mipSW = 0 при экспорте.
        /// </summary>
        internal static string Desc_PickMask {
            get {
                return ResourceManager.GetString("Desc_PickMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание расположение виджета.
        /// </summary>
        internal static string Desc_Placement {
            get {
                return ResourceManager.GetString("Desc_Placement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приоритет отображения (также влияет на обработку мышиных событий) виджета в списке виджетов своего родителя. То есть с помощью этого поля можно сформировать иерархию отображения виджетов всего аддона.
        /// </summary>
        internal static string Desc_Priority {
            get {
                return ResourceManager.GetString("Desc_Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Уведомление о наведении на виджет. (Кроме виджетов со специальной обработкой - кнопок и т.д.).
        /// </summary>
        internal static string Desc_ReactionOnPointing {
            get {
                return ResourceManager.GetString("Desc_ReactionOnPointing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Уведомление о прокрутке колёсика мыши вниз.
        /// </summary>
        internal static string Desc_ReactionWheelDown {
            get {
                return ResourceManager.GetString("Desc_ReactionWheelDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Уведомление о прокрутке колёсика мыши вверх.
        /// </summary>
        internal static string Desc_ReactionWheelUp {
            get {
                return ResourceManager.GetString("Desc_ReactionWheelUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Звук на скрытие виджета.
        /// </summary>
        internal static string Desc_SoundHide {
            get {
                return ResourceManager.GetString("Desc_SoundHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Звук на начатое отображение виджета.
        /// </summary>
        internal static string Desc_SoundShow {
            get {
                return ResourceManager.GetString("Desc_SoundShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Задаёт порядок обхода контролов по клавише Tab. По умолчанию 0(не учавствует в обходе). Для участия в обходе значение должно быть больше 0.
        /// </summary>
        internal static string Desc_TabOrder {
            get {
                return ResourceManager.GetString("Desc_TabOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текстура с альфой. Используется для задания маски, по которой будет обрезана основная текстура данного контрола и всех его детей.
        /// </summary>
        internal static string Desc_TextureMask {
            get {
                return ResourceManager.GetString("Desc_TextureMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Является ли виджет прозрачным для ввода. По умолчанию false.
        /// </summary>
        internal static string Desc_TransparentInput {
            get {
                return ResourceManager.GetString("Desc_TransparentInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Виден ли виджет. По умолчанию true. если виджет не виден, то он недоступен и для реакций.
        /// </summary>
        internal static string Desc_Visible {
            get {
                return ResourceManager.GetString("Desc_Visible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дочерние виджеты. Почти каждый виджет может содержать дочерние виджеты, за исключением особых случаев типа слайдера и т.п. Дочерние виджеты отображаются поверх родителя и перехватывают реакции (если они объявлены и на них подписаны обработчики) раньше родительского виджета за исключением особых случаев.
        /// </summary>
        internal static string Desc_Widgets {
            get {
                return ResourceManager.GetString("Desc_Widgets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нужно ли обрезать содержимое, включая дочерние виджеты, по границам данного. По умолчанию false.
        /// </summary>
        internal static string Desc_СlipContent {
            get {
                return ResourceManager.GetString("Desc_СlipContent", resourceCulture);
            }
        }
    }
}
